spring:
  mail:
    username: everycampingshop@gmail.com
    password: ENC(uvepi/z4e7XQ0Y9ipf0uXKx0qcTPET2PkzO24zTyHJs=)
  jpa:
    hibernate:
      ddl-auto: update

aws:
  s3:
    bucketname: everycamping
    endpointurl: https://everycamping.s3.ap-northeast-2.amazonaws.com
    accesskey: ENC(le4eWEUA0mhIz702w6DaD34OYeyBIHpRRd6NIvUKjSQ=)
    secretkey: ENC(u635qCpiz8mHZu7Go4oLVM7NCcil3uXp0X6kl+pf2+1mUVkekfULpy6+Et8f+sEvJrKhpKGTz2c=)

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: root
    password: 1
    url: jdbc:mariadb://localhost:3306/everycamping
  redis:
    host: localhost
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: admin
    password: ENC(EZ8FmMfnQZDF5Buyzvqhcuhxzy6Imlsy)
    url: jdbc:mariadb://everycamping-rds.cklf3l4rcuqo.ap-northeast-2.rds.amazonaws.com:3306/everycamping
  redis:
    host: ec2-43-200-2-48.ap-northeast-2.compute.amazonaws.com
